import aiStartup from "@/assets/images/ai-startup-landing-page.png";
import darkSaas from "@/assets/images/dark-saas-landing-page.png";
import lightSaas from "@/assets/images/light-saas-landing-page.png";
import { StaticImageData } from "next/image";

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  readTime: string;
  image: StaticImageData;
  content: string; // HTML or Markdown content
}

export const blogPosts: BlogPost[] = [
  {
    slug: "rise-of-generative-ai",
    title: "The Rise of Generative AI: Beyond the Hype",
    excerpt:
      "Deep dive into Large Language Models, Transformer architecture, and how they are reshaping the software engineering landscape.",
    date: "Oct 24, 2024",
    category: "Artificial Intelligence",
    readTime: "5 min read",
    image: aiStartup, 
    content: `
      <h2>The New Era of Intelligence</h2>
      <p>Generative AI is not just a buzzword; it's a fundamental shift in how we interact with information. From parsing complex documentation to generating boilerplate code, LLMs are acting as force multipliers for developers.</p>
      
      <h3>The Transformer Architecture</h3>
      <p>At the core of this revolution lies the Transformer. Unlike previous RNNs, Transformers process data in parallel, allowing for massive scale and context retention. The 'Attention Mechanism' is the key differentiator.</p>

      <pre><code class="language-python">
# Pseudo-code for Attention Mechanism
def attention(Q, K, V):
    return softmax((Q @ K.T) / sqrt(d_k)) @ V
      </code></pre>

      <h3>Impact on Development</h3>
      <p>Tools like Github Copilot and Cursor are changing the loop. We aren't just writing syntax anymore; we are reviewing and orchestrating logic generated by AI.</p>
    `,
  },
  {
    slug: "vector-databases-explained",
    title: "Vector Databases: The Memory of AI",
    excerpt:
      "Understanding High-Dimensional Vector Spaces, Embeddings, and how to build efficient RAG (Retrieval-Augmented Generation) pipelines.",
    date: "Nov 12, 2024",
    category: "Database",
    readTime: "7 min read",
    image: darkSaas,
    content: `
      <h2>Why Traditional SQL Isn't Enough</h2>
      <p>SQL databases are great for exact matches. But how do you query for "conceptually similar" data? This is where Vector Databases come in.</p>
      
      <h3>Embeddings Explained</h3>
      <p>An embedding is a vector (list of numbers) that represents semantic meaning. Words like "King" and "Queen" will be closer in vector space than "King" and "Apple".</p>

      <h3>Building a RAG Pipeline</h3>
      <ul>
        <li><strong>Chunking:</strong> Split your data into manageable pieces.</li>
        <li><strong>Embedding:</strong> Pass chunks through a model (like OpenAI Ada).</li>
        <li><strong>Indexing:</strong> Store vectors in Pinecone/Weaviate.</li>
        <li><strong>Retrieval:</strong> Query the DB with the user's prompt vector.</li>
      </ul>
    `,
  },
  {
    slug: "future-of-web-dev",
    title: "The Future of Web Development in 2025",
    excerpt:
      "Server Components, Edge Rendering, and the convergence of AI with UI/UX. How web apps are becoming smarter and faster.",
    date: "Dec 05, 2024",
    category: "Web Development",
    readTime: "4 min read",
    image: lightSaas,
    content: `
      <h2>The Shift to the Edge</h2>
      <p>Vercel and Cloudflare are pushing compute closer to the user. Combined with React Server Components, we can now deliver dynamic, personalized content with static-like performance.</p>
      
      <h3>AI-Generated UI</h3>
      <p>We are moving towards 'Generative UI' - where the interface itself adapts based on user intent. Imagine a dashboard that reconfigures itself based on what you are looking for.</p>
    `,
  },
];
